### ISSUE TITLE
OSI License

### ISSUE THREAD

**Issue by JeremyWildsmith** [nettitude/SimplePELoader#1]
Hello,

Would it be possible for this to be licensed under a OSI license? Like MIT?

Thanks!

**Comment by Coder666** [comment]
Why is the current licence unacceptable to you?

**Comment by JeremyWildsmith** [comment]
Current license is fine, but if there is an OSI license that accomplishes the same thing, it would be nice to have it licensed under that instead (or as well.) A lot of projects I work on are approved for incorporating OSI licensed work by default, and then anything else basically needs to be approved by a lawyer. Which makes me hesitant to prototype with the work.

Ofcourse, its up to you how you want to license it. I appreciate your decision either way.

Thanks!

**Comment by Coder666** [comment]
I will tag the repository to make it clearer in the future

Please note there are no plans to change to a different licence
